### PR TITLE
changed drools and optaplanner version

### PR DESCRIPTION
**Pull request by mbiarnes**
upgrade of OptaPlanner and Drools version

### CODE REVIEW

**Review by dupliaka — APPROVED** [review]

**Comment by hellowdan** [comment]
@gitgabrio here you can see some logs if you need it

**Comment by gitgabrio** [comment]
> @gitgabrio here you can see some logs if you need it

:+1:

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by hellowdan** [comment]
Jenkins retest this

**Pull request closed without merging**
