### PR TITLE
[DROOLS-7361] Add benchmarks for drools-reliability

### PR DESCRIPTION
**Pull request by tkobayas**
Local test results
```
Benchmark                 (factsNr)  (joinsNr)    (mode)  (rulesNr)  Mode  Cnt    Score   Error  Units
FireOnlyBenchmark.test           10        N/A      NONE        192    ss  200    1.474 ± 0.090  ms/op
FireOnlyBenchmark.test           10        N/A  EMBEDDED        192    ss  200    2.408 ± 0.117  ms/op
FireOnlyBenchmark.test           10        N/A    REMOTE        192    ss  200    2.842 ± 0.235  ms/op
FireOnlyBenchmark.test          100        N/A      NONE        192    ss  200    4.901 ± 0.216  ms/op
FireOnlyBenchmark.test          100        N/A  EMBEDDED        192    ss  200    7.799 ± 0.201  ms/op
FireOnlyBenchmark.test          100        N/A    REMOTE        192    ss  200   12.299 ± 0.287  ms/op
FireOnlyBenchmark.test         1000        N/A      NONE        192    ss  200   35.917 ± 0.697  ms/op
FireOnlyBenchmark.test         1000        N/A  EMBEDDED        192    ss  200   70.993 ± 0.749  ms/op
FireOnlyBenchmark.test         1000        N/A    REMOTE        192    ss  200  102.626 ± 1.135  ms/op
InsertOnlyBenchmark.test         10          3      NONE        768    ss  200    0.042 ± 0.003  ms/op
InsertOnlyBenchmark.test         10          3  EMBEDDED        768    ss  200    2.396 ± 0.207  ms/op
InsertOnlyBenchmark.test         10          3    REMOTE        768    ss  200    2.632 ± 0.085  ms/op
InsertOnlyBenchmark.test        100          3      NONE        768    ss  200    0.159 ± 0.007  ms/op
InsertOnlyBenchmark.test        100          3  EMBEDDED        768    ss  200   12.889 ± 0.208  ms/op
InsertOnlyBenchmark.test        100          3    REMOTE        768    ss  200   20.155 ± 0.478  ms/op
InsertOnlyBenchmark.test       1000          3      NONE        768    ss  200    1.106 ± 0.159  ms/op
InsertOnlyBenchmark.test       1000          3  EMBEDDED        768    ss  200  135.086 ± 2.161  ms/op
InsertOnlyBenchmark.test       1000          3    REMOTE        768    ss  200  178.414 ± 2.866  ms/op
```

### CODE REVIEW

**Comment by tkobayas** [comment]
Note `FireOnlyBenchmark` is also affected by reliability mode (expected), because objects are put into a cache in `onWorkingMemoryAction`.

**Comment by tkobayas** [comment]
Probably I need to wait for a day to be able to download `drools-reliability-core` and `drools-reliability-infinispan`, which were recently added.

**Comment by tkobayas** [comment]
Probably need rebase after https://github.com/kiegroup/kie-benchmarks/pull/229

**Comment by dupliaka** [comment]
> Note `FireOnlyBenchmark` is also affected by reliability mode (expected), because objects are put into a cache in `onWorkingMemoryAction`.

That is interesting, there is a nice feature in JMH to build a firegraph BTW 
https://github.com/kiegroup/kie-benchmarks/blob/3860c03e6cbe168252ad033187edf10357871900/optaplanner-benchmarks/README.md#performance-profiling-with-jmh

**Review by mariofusco — APPROVED** [review]

**Comment by dupliaka** [comment]
@pibizza should I create a new test set in Horreum to start tracking regressions for this module?

**Comment by pibizza** [comment]
@hellowdan this is probably for you to decide...

**Comment by hellowdan** [comment]
Hello all,
Yes @dupliaka it would be nice to add a test to Horreum monitoring.

**Pull request merged**
