### PR TITLE
[DROOLS-7111] Fixing benchmarks. Add compilation benchmarks

### PR DESCRIPTION
**Pull request by gitgabrio**
@mariofusco @tkobayas @hellowdan 

**JIRA**: 
[link](https://issues.redhat.com/browse/DROOLS-7111)

### CODE REVIEW

**Comment by hellowdan** [comment]
Hi @gitgabrio . It seems that the compilation failure is fixed, but I'm getting a runtime error when I try to run the PMML benchmarks. I used the following simple command line:
java -jar ./drools-benchmarks/target/drools-benchmarks.jar -foe true -rf json -rff jmh-result.json org.drools.benchmarks.pmml.runtime.*

**Review by hellowdan — CHANGES_REQUESTED** [review]
Benchmark execution is throwing java.io.IOException.

**Comment by gitgabrio** [comment]
Hi @hellowdan could you pls paste here the stacktrace ?

**Comment by hellowdan** [comment]
> Hi @hellowdan could you pls paste here the stacktrace ?

Hi @gitgabrio sure, you can find it here: https://gist.github.com/hellowdan/a6b5d66be2c9efed6cb3e40de25e5b9c

**Comment by gitgabrio** [comment]
HI @hellowdan 
[this](https://github.com/kiegroup/drools/pull/4633) should fix the bug, but @tkobayas is already working on a [refactoring](https://github.com/kiegroup/drools/pull/4618) that would completely solve the issue at root, and would also "clean up" the code in the benchmarks.
If possible, I would prefer to postpone the kie-benchmark fix after the PR from Toshiya, otherwise we have to 1) merge my PR on main; 2) merge the current kie-benchmark code; 3) merge the PR from Toshiya 4) modify again the kie-benchmark code.
Anyway, let me know what is better from your point of view.

**Comment by hellowdan** [comment]
> modify again the kie-benchmark code

As we will need to modify the benchmark code again, I think we can wait for the proper fix. We can discuss it again next Monday when we can change the plans, if needed.

**Comment by gitgabrio** [comment]
Hi @hellowdan 
Cool. I'll update kie-benchmarks as soon as DROOLS-7090 is merged and I push commit then.

**Review by dupliaka — APPROVED** [review]

**Comment by gitgabrio** [comment]
Hi @hellowdan : I've fixed the code.
I tried locally issuing commands like:
` java -jar ./drools-benchmarks/target/drools-benchmarks.jar -foe true -rf json -rff jmh-result.json org.drools.benchmarks.pmml.runtime.*` (or similar).
I also created some `compilation` benchmarks <- @mariofusco

**Comment by hellowdan** [comment]
Thanks @gitgabrio !

**Comment by hellowdan** [comment]
@gitgabrio unfortunately I haven't been able to review the recent commits in time, I hope everything goes well. I will verify this in more detail and if there is any issue, I will let you know.

**Pull request merged**
