### PR TITLE
BAQE-2278 - adds an anchor (or default) parameter to turtle benchmarks in order to keep all the arrays with the same size in Horreum

### PR DESCRIPTION
**Pull request by hellowdan**
- it may be necessary to add it to other benchmarks as well (like DMN)

### CODE REVIEW

**Comment by hellowdan** [comment]
@dupliaka @MichalCervenansky @winklerm please take a look :)

**Comment by MichalCervenansky** [comment]
While I don't mind idea of dummy parameter, could you clarify where was the issue? Removing Extractor for params from Schema wouldn't help?
Screenshot from 2022-05-18 10-47-03

**Comment by dupliaka** [comment]
> While I don't mind idea of dummy parameter, could you clarify where was the issue? Removing Extractor for params from Schema wouldn't help? Screenshot from 2022-05-18 10-47-03

As I remember from the last discussion the problem was that if you use js script to find the result and you do not have parameters in tests then Horreum will not be able to process that

Please do not remove parameters from jmh schema since that is shared and standard jmh parameter

Other workaround could be just checking if the param === null

**Comment by MichalCervenansky** [comment]
Ok, I see. Then whatever works for you. Maybe it is something worth reporting to Radim.

@dupliaka, actually even though jmh schema is shared, the extractors are stored in Labels and every test has separate labels, so editing them shouldn't be an issue. I have to say, that after moving extractors to Labels there is a lot of duplicity and editing extractor will be a pain.

**Review by MichalCervenansky — APPROVED** [review]

**Pull request closed without merging**
