### PR TITLE
[DROOLS-7523] allow parallel evaluation of LHS part of rules with seq…

### PR DESCRIPTION
**Pull request by mariofusco**
…uential firing of consequences

### CODE REVIEW

**Review by dupliaka — COMMENTED** [review]
Thanks for updating the tests

In this PR you have updated kieBaseOption for parallel execution.
MultithreadEvaluationOption is not boolean anymore.
MultithreadEvaluationOption.NO is sequential execution
MultithreadEvaluationOption.YES is parallel_evaluation execution

I didn't find anything about ParallelExecutionOption in the documentation: https://docs.drools.org/8.42.0.Final/drools-docs/drools/rule-engine/index.html#phreak-algorithm-con_rule-engine

What is the difference bw parallel_evaluation and fully parallel?

**Comment by mariofusco** [comment]
> I didn't find anything about ParallelExecutionOption in the documentation: https://docs.drools.org/8.42.0.Final/drools-docs/drools/rule-engine/index.html#phreak-algorithm-con_rule-engine
> 
> What is the difference bw parallel_evaluation and fully parallel?

It will be in 8.43.0.Final. I documented it with this commit https://github.com/kiegroup/drools/commit/974c1e88a7ebab2d284865ff8a417af803715382

**Comment by dupliaka** [comment]
> > I didn't find anything about ParallelExecutionOption in the documentation: https://docs.drools.org/8.42.0.Final/drools-docs/drools/rule-engine/index.html#phreak-algorithm-con_rule-engine
> > What is the difference bw parallel_evaluation and fully parallel?
> 
> It will be in 8.43.0.Final. I documented it with this commit [kiegroup/drools@974c1e8](https://github.com/kiegroup/drools/commit/974c1e88a7ebab2d284865ff8a417af803715382)

Thanks a lot! Could you please update the comments at TurtleFusionBenchmarkRunner.class and TurtleBenchmarkRunner.class as well?

"Then run, JVM option -Ddrools.multithreadEvaluation=true must be set." 

If I got it right it should be  -Ddrools.parallelExecution=parallel_evaluation

**Comment by mariofusco** [comment]
> "Then run, JVM option -Ddrools.multithreadEvaluation=true must be set."
> 
> If I got it right it should be -Ddrools.parallelExecution=parallel_evaluation

Done.

**Review by dupliaka — APPROVED** [review]

**Pull request merged**
